apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "13.0.0"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: kubeaid
  source:
    path: k8s/kubeaid-demo-local/sealed-secrets
    repoURL: https://github.com/teterevlev/kubeaid-config
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy: {}
