apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
  name: mdraid
  namespace: monitoring
spec:
  groups:
  - name: mdraid-status
    rules:
    - alert: HostRaidDiskDegraded
      annotations:
        description: RAID array {{ $labels.device }} on {{ $labels.instance }} is in degraded state due to one or more disks failures. Number of spare drives is insufficient to fix issue automatically
        summary: RAID Array is degraded.
      expr: (node_md_state{state="inactive"} > 0) * on(instance) group_left (pod) node_uname_info{nodename=~".+"}
      for: 15m
      labels:
        alert_id: HostRaidDiskDegraded
        severity: critical
    - alert: HostRaidDiskFailure
      annotations:
        description: At least one disk in RAID array {{ $labels.device }} on {{ $labels.instance }} failed. Array {{ $labels.device }} needs attention and possibly a disk swap
        summary: Host RAID disk failure on instance.
      expr: (node_md_disks{state="failed"} > 0) * on(instance) group_left (nodename) node_uname_info{nodename=~".+"}
      for: 15m
      labels:
        alert_id: HostRaidDiskFailure
        severity: critical
